[package]
name = "brace-ec"
version = "0.0.0"
description = "An evolutionary computation framework"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://brace.rs"
repository = "https://github.com/brace-rs/brace-ec"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
array-util = "1.0.2"
atomic-traits = "0.4.0"
ghost = "0.1.18"
itertools = "0.14.0"
num-traits = "0.2.19"
ordered-float = "4.6.0"
rand = "0.9.0"
rayon = "1.10.0"
thiserror = "2.0.9"

[dependencies.bytemuck]
version = "1.21.0"
features = ["derive", "transparentwrapper_extra"]
